language: perl
dist: trusty
perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"
 - "5.20"
 - "5.22"
 - "5.24"
 - "5.26"
 - "5.28"
 - "5.30"

install:
  - dzil authordeps --missing | cpanm --notest --no-skip-satisfied
  - dzil listdeps --author --missing | cpanm --notest --no-skip-satisfied

script:
  - dzil test --author --release
